DROP TABLE IF EXISTS sake_images CASCADE;
DROP TABLE IF EXISTS match_requests CASCADE;
DROP TABLE IF EXISTS bookmarks CASCADE;
DROP TABLE IF EXISTS drink_logs CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sake_tag_links CASCADE;
DROP TABLE IF EXISTS sake_tags CASCADE;
DROP TABLE IF EXISTS sakes CASCADE;

DROP TYPE IF EXISTS match_status;
DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS sake_category;
