name: sake-hack

services:
  postgis:
    build: ./postgres
    platform: linux/amd64
    container_name: sake-hack-db
    restart: always
    volumes:
      - type: volume
        source: sake-hack-db
        target: /var/lib/postgresql
      - type: bind
        source: ./postgres/config/default.conf
        target: /etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    env_file:
      - .env
    ports:
      - ${POSTGRES_HOST_PORT:-5432}:5432
    networks:
      - sake_hack_network

  pgweb:
    image: sosedoff/pgweb
    container_name: sake-hack-pgweb
    restart: always
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      PGWEB_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@sake-hack-db:5432/${POSTGRES_DB}?sslmode=disable"
    networks:
      - sake_hack_network

  valkey:
    image: valkey/valkey:9.0.0
    container_name: sake-hack-valkey
    restart: always
    volumes:
      - type: volume
        source: sake-hack-valkey-data
        target: /data
    ports:
      - ${VALKEY_HOST_PORT:-6379}:6379
    env_file:
      - .env
    command: >
      valkey-server
      --appendonly yes
      --requirepass ${VALKEY_PASSWORD}
    networks:
      - sake_hack_network

  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.83
    container_name: sake-hack-rustfs
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLED=true
      - RUSTFS_SERVER_URL=http://localhost:9000
      - RUSTFS_ADDRESS=:9000
      - RUSTFS_CONSOLE_ADDRESS=:9001
      - RUSTFS_CORS_ALLOW_ORIGIN=*
      - RUSTFS_CORS_ALLOW_METHODS=*
      - RUSTFS_CORS_ALLOW_HEADERS=*
      - RUSTFS_CORS_EXPOSE_HEADERS=*
      - RUSTFS_CORS_ALLOW_CREDENTIALS=false
    volumes:
      - type: volume
        source: sake-hack-rustfs-data
        target: /data
    networks:
      - sake_hack_network

volumes:
  sake-hack-db:
  sake-hack-valkey-data:
  sake-hack-rustfs-data:

networks:
  sake_hack_network:
    name: sake_hack_network
    driver: bridge
