// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package sqlc

import (
	"context"
)

const createLike = `-- name: CreateLike :exec
INSERT INTO likes (sake_id, token) VALUES ($1, $2)
ON CONFLICT (sake_id, token) DO NOTHING
`

type CreateLikeParams struct {
	SakeID int32  `db:"sake_id" json:"sake_id"`
	Token  string `db:"token" json:"token"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.db.Exec(ctx, createLike, arg.SakeID, arg.Token)
	return err
}

const deleteLike = `-- name: DeleteLike :execrows
DELETE FROM likes WHERE sake_id = $1 AND token = $2
`

type DeleteLikeParams struct {
	SakeID int32  `db:"sake_id" json:"sake_id"`
	Token  string `db:"token" json:"token"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLike, arg.SakeID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const existsLike = `-- name: ExistsLike :one
SELECT EXISTS(SELECT 1 FROM likes WHERE sake_id = $1 AND token = $2) AS is_liked
`

type ExistsLikeParams struct {
	SakeID int32  `db:"sake_id" json:"sake_id"`
	Token  string `db:"token" json:"token"`
}

func (q *Queries) ExistsLike(ctx context.Context, arg ExistsLikeParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsLike, arg.SakeID, arg.Token)
	var is_liked bool
	err := row.Scan(&is_liked)
	return is_liked, err
}

const getLikeCount = `-- name: GetLikeCount :one
SELECT COUNT(*) AS like_count FROM likes WHERE sake_id = $1
`

func (q *Queries) GetLikeCount(ctx context.Context, sakeID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getLikeCount, sakeID)
	var like_count int64
	err := row.Scan(&like_count)
	return like_count, err
}
