// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: master.sql

package sqlc

import (
	"context"
)

const listBreweries = `-- name: ListBreweries :many
SELECT id, name, origin_country, origin_region, latitude, longitude
FROM breweries
WHERE ($2::TEXT IS NULL OR name LIKE '%' || $2 || '%')
ORDER BY id
LIMIT $1
`

type ListBreweriesParams struct {
	Limit   int32   `db:"limit" json:"limit"`
	Keyword *string `db:"keyword" json:"keyword"`
}

type ListBreweriesRow struct {
	ID            int32    `db:"id" json:"id"`
	Name          string   `db:"name" json:"name"`
	OriginCountry string   `db:"origin_country" json:"origin_country"`
	OriginRegion  *string  `db:"origin_region" json:"origin_region"`
	Latitude      *float64 `db:"latitude" json:"latitude"`
	Longitude     *float64 `db:"longitude" json:"longitude"`
}

func (q *Queries) ListBreweries(ctx context.Context, arg ListBreweriesParams) ([]ListBreweriesRow, error) {
	rows, err := q.db.Query(ctx, listBreweries, arg.Limit, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBreweriesRow
	for rows.Next() {
		var i ListBreweriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OriginCountry,
			&i.OriginRegion,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrinkStyles = `-- name: ListDrinkStyles :many
SELECT id, name, description FROM drink_styles ORDER BY id
`

type ListDrinkStylesRow struct {
	ID          int32   `db:"id" json:"id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
}

func (q *Queries) ListDrinkStyles(ctx context.Context) ([]ListDrinkStylesRow, error) {
	rows, err := q.db.Query(ctx, listDrinkStyles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDrinkStylesRow
	for rows.Next() {
		var i ListDrinkStylesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKinds = `-- name: ListKinds :many
SELECT id, name FROM sake_kinds ORDER BY id
`

type ListKindsRow struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) ListKinds(ctx context.Context) ([]ListKindsRow, error) {
	rows, err := q.db.Query(ctx, listKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKindsRow
	for rows.Next() {
		var i ListKindsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
