// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

// マッチングリクエスト状態: PENDING/ACCEPTED/REJECTED
type MatchStatus string

const (
	MatchStatusPENDING  MatchStatus = "PENDING"
	MatchStatusACCEPTED MatchStatus = "ACCEPTED"
	MatchStatusREJECTED MatchStatus = "REJECTED"
)

func (e *MatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchStatus(s)
	case string:
		*e = MatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchStatus: %T", src)
	}
	return nil
}

type NullMatchStatus struct {
	MatchStatus MatchStatus `json:"match_status"`
	Valid       bool        `json:"valid"` // Valid is true if MatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchStatus), nil
}

func (e MatchStatus) Valid() bool {
	switch e {
	case MatchStatusPENDING,
		MatchStatusACCEPTED,
		MatchStatusREJECTED:
		return true
	}
	return false
}

func AllMatchStatusValues() []MatchStatus {
	return []MatchStatus{
		MatchStatusPENDING,
		MatchStatusACCEPTED,
		MatchStatusREJECTED,
	}
}

// お酒カテゴリ: JAPANESE_SAKE/SHOCHU/AWAMORI/BEER/WINE/FRUIT_WINE/LIQUEUR/NON_ALCOHOL/OTHER
type SakeCategory string

const (
	SakeCategoryJAPANESESAKE SakeCategory = "JAPANESE_SAKE"
	SakeCategorySHOCHU       SakeCategory = "SHOCHU"
	SakeCategoryAWAMORI      SakeCategory = "AWAMORI"
	SakeCategoryBEER         SakeCategory = "BEER"
	SakeCategoryWINE         SakeCategory = "WINE"
	SakeCategoryFRUITWINE    SakeCategory = "FRUIT_WINE"
	SakeCategoryLIQUEUR      SakeCategory = "LIQUEUR"
	SakeCategoryNONALCOHOL   SakeCategory = "NON_ALCOHOL"
	SakeCategoryOTHER        SakeCategory = "OTHER"
)

func (e *SakeCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SakeCategory(s)
	case string:
		*e = SakeCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for SakeCategory: %T", src)
	}
	return nil
}

type NullSakeCategory struct {
	SakeCategory SakeCategory `json:"sake_category"`
	Valid        bool         `json:"valid"` // Valid is true if SakeCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSakeCategory) Scan(value interface{}) error {
	if value == nil {
		ns.SakeCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SakeCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSakeCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SakeCategory), nil
}

func (e SakeCategory) Valid() bool {
	switch e {
	case SakeCategoryJAPANESESAKE,
		SakeCategorySHOCHU,
		SakeCategoryAWAMORI,
		SakeCategoryBEER,
		SakeCategoryWINE,
		SakeCategoryFRUITWINE,
		SakeCategoryLIQUEUR,
		SakeCategoryNONALCOHOL,
		SakeCategoryOTHER:
		return true
	}
	return false
}

func AllSakeCategoryValues() []SakeCategory {
	return []SakeCategory{
		SakeCategoryJAPANESESAKE,
		SakeCategorySHOCHU,
		SakeCategoryAWAMORI,
		SakeCategoryBEER,
		SakeCategoryWINE,
		SakeCategoryFRUITWINE,
		SakeCategoryLIQUEUR,
		SakeCategoryNONALCOHOL,
		SakeCategoryOTHER,
	}
}

// ユーザーロール: SHOP(主催者)/USER(参加者)
type UserRole string

const (
	UserRoleSHOP UserRole = "SHOP"
	UserRoleUSER UserRole = "USER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleSHOP,
		UserRoleUSER:
		return true
	}
	return false
}

func AllUserRoleValues() []UserRole {
	return []UserRole{
		UserRoleSHOP,
		UserRoleUSER,
	}
}

// ブックマーク
type Bookmark struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// ユーザーID
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// 飲酒記録
type DrinkLog struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// ユーザーID
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// 飲んだ日時
	DrankAt pgtype.Timestamptz `db:"drank_at" json:"drank_at"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// お酒へのいいね
type Like struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// 一時トークン（匿名識別用, 必須）
	Token string `db:"token" json:"token"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// マッチングリクエスト
type MatchRequest struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// リクエスト送信者ID
	FromUserID pgtype.UUID `db:"from_user_id" json:"from_user_id"`
	// リクエスト受信者ID
	ToUserID pgtype.UUID `db:"to_user_id" json:"to_user_id"`
	// ステータス（PENDING/ACCEPTED/REJECTED）
	Status MatchStatus `db:"status" json:"status"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// 更新日時
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// お酒マスタ
type Sake struct {
	// 酒ID
	ID pgtype.UUID `db:"id" json:"id"`
	// 酒名（最大50文字, 必須）
	Name string `db:"name" json:"name"`
	// ふりがな（最大100文字）
	Phonetic *string `db:"phonetic" json:"phonetic"`
	// 酒カテゴリ（必須）
	Category SakeCategory `db:"category" json:"category"`
	// アルコール度数（0.0-100.0）
	AlcoholPercentage pgtype.Numeric `db:"alcohol_percentage" json:"alcohol_percentage"`
	// 最大容量（ml）
	VolumeMax *int32 `db:"volume_max" json:"volume_max"`
	// 残り容量（%: 0-100）
	VolumeRemain *int32 `db:"volume_remain" json:"volume_remain"`
	// 産地
	Region *string `db:"region" json:"region"`
	// 価格（円）
	Price *int32 `db:"price" json:"price"`
	// メモ（最大500文字）
	Memo *string `db:"memo" json:"memo"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// 更新日時
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// お酒画像
type SakeImage struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// 画像オブジェクトキー
	ImageKey string `db:"image_key" json:"image_key"`
	// 表示順（0始まり）
	SortOrder int32 `db:"sort_order" json:"sort_order"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// お酒タグマスタ
type SakeTag struct {
	// タグID
	ID pgtype.UUID `db:"id" json:"id"`
	// タグ文字列（最大50文字, 必須）
	Tag string `db:"tag" json:"tag"`
}

// お酒とタグの関連
type SakeTagLink struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// タグID
	SakeTagID pgtype.UUID `db:"sake_tag_id" json:"sake_tag_id"`
}

// ユーザー
type User struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// メールアドレス（必須, 一意）
	Email string `db:"email" json:"email"`
	// パスワードハッシュ（必須）
	PasswordHash string `db:"password_hash" json:"password_hash"`
	// 表示名（任意）
	DisplayName *string `db:"display_name" json:"display_name"`
	// ロール（SHOP/USER）
	Role UserRole `db:"role" json:"role"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
