// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

// マッチングリクエスト状態: PENDING/ACCEPTED/REJECTED
type MatchStatusType string

const (
	MatchStatusTypePENDING  MatchStatusType = "PENDING"
	MatchStatusTypeACCEPTED MatchStatusType = "ACCEPTED"
	MatchStatusTypeREJECTED MatchStatusType = "REJECTED"
)

func (e *MatchStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchStatusType(s)
	case string:
		*e = MatchStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchStatusType: %T", src)
	}
	return nil
}

type NullMatchStatusType struct {
	MatchStatusType MatchStatusType `json:"match_status_type"`
	Valid           bool            `json:"valid"` // Valid is true if MatchStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.MatchStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchStatusType), nil
}

func (e MatchStatusType) Valid() bool {
	switch e {
	case MatchStatusTypePENDING,
		MatchStatusTypeACCEPTED,
		MatchStatusTypeREJECTED:
		return true
	}
	return false
}

func AllMatchStatusTypeValues() []MatchStatusType {
	return []MatchStatusType{
		MatchStatusTypePENDING,
		MatchStatusTypeACCEPTED,
		MatchStatusTypeREJECTED,
	}
}

// ユーザーロール: SHOP(主催者)/USER(参加者)
type RoleType string

const (
	RoleTypeSHOP RoleType = "SHOP"
	RoleTypeUSER RoleType = "USER"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType `json:"role_type"`
	Valid    bool     `json:"valid"` // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

func (e RoleType) Valid() bool {
	switch e {
	case RoleTypeSHOP,
		RoleTypeUSER:
		return true
	}
	return false
}

func AllRoleTypeValues() []RoleType {
	return []RoleType{
		RoleTypeSHOP,
		RoleTypeUSER,
	}
}

// お酒カテゴリ: JAPANESE_SAKE/SHOCHU/AWAMORI/BEER/WINE/FRUIT_WINE/LIQUEUR/NON_ALCOHOL/OTHER
type SakeCategoryType string

const (
	SakeCategoryTypeJAPANESESAKE SakeCategoryType = "JAPANESE_SAKE"
	SakeCategoryTypeSHOCHU       SakeCategoryType = "SHOCHU"
	SakeCategoryTypeAWAMORI      SakeCategoryType = "AWAMORI"
	SakeCategoryTypeBEER         SakeCategoryType = "BEER"
	SakeCategoryTypeWINE         SakeCategoryType = "WINE"
	SakeCategoryTypeFRUITWINE    SakeCategoryType = "FRUIT_WINE"
	SakeCategoryTypeLIQUEUR      SakeCategoryType = "LIQUEUR"
	SakeCategoryTypeNONALCOHOL   SakeCategoryType = "NON_ALCOHOL"
	SakeCategoryTypeOTHER        SakeCategoryType = "OTHER"
)

func (e *SakeCategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SakeCategoryType(s)
	case string:
		*e = SakeCategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for SakeCategoryType: %T", src)
	}
	return nil
}

type NullSakeCategoryType struct {
	SakeCategoryType SakeCategoryType `json:"sake_category_type"`
	Valid            bool             `json:"valid"` // Valid is true if SakeCategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSakeCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.SakeCategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SakeCategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSakeCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SakeCategoryType), nil
}

func (e SakeCategoryType) Valid() bool {
	switch e {
	case SakeCategoryTypeJAPANESESAKE,
		SakeCategoryTypeSHOCHU,
		SakeCategoryTypeAWAMORI,
		SakeCategoryTypeBEER,
		SakeCategoryTypeWINE,
		SakeCategoryTypeFRUITWINE,
		SakeCategoryTypeLIQUEUR,
		SakeCategoryTypeNONALCOHOL,
		SakeCategoryTypeOTHER:
		return true
	}
	return false
}

func AllSakeCategoryTypeValues() []SakeCategoryType {
	return []SakeCategoryType{
		SakeCategoryTypeJAPANESESAKE,
		SakeCategoryTypeSHOCHU,
		SakeCategoryTypeAWAMORI,
		SakeCategoryTypeBEER,
		SakeCategoryTypeWINE,
		SakeCategoryTypeFRUITWINE,
		SakeCategoryTypeLIQUEUR,
		SakeCategoryTypeNONALCOHOL,
		SakeCategoryTypeOTHER,
	}
}

// ブックマーク
type Bookmark struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// ユーザーID
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// 飲酒記録
type DrinkLog struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// ユーザーID
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// 飲んだ日時
	DrankAt pgtype.Timestamptz `db:"drank_at" json:"drank_at"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// お酒へのいいね
type Like struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// 一時トークン（匿名識別用, 必須）
	Token string `db:"token" json:"token"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// マッチングリクエスト
type MatchRequest struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// リクエスト送信者ID
	FromUserID pgtype.UUID `db:"from_user_id" json:"from_user_id"`
	// リクエスト受信者ID
	ToUserID pgtype.UUID `db:"to_user_id" json:"to_user_id"`
	// ステータス（PENDING/ACCEPTED/REJECTED）
	Status MatchStatusType `db:"status" json:"status"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// 更新日時
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// お酒マスタ
type Sake struct {
	// 酒ID
	ID pgtype.UUID `db:"id" json:"id"`
	// 酒名（最大50文字, 必須）
	Name string `db:"name" json:"name"`
	// ふりがな（最大100文字）
	Phonetic *string `db:"phonetic" json:"phonetic"`
	// 酒カテゴリ（必須）
	Category SakeCategoryType `db:"category" json:"category"`
	// アルコール度数（0.0-100.0）
	AlcoholPercentage pgtype.Numeric `db:"alcohol_percentage" json:"alcohol_percentage"`
	// 最大容量（ml）
	VolumeMax *int32 `db:"volume_max" json:"volume_max"`
	// 残り容量（%: 0-100）
	VolumeRemain *int32 `db:"volume_remain" json:"volume_remain"`
	// 産地
	Region *string `db:"region" json:"region"`
	// 価格（円）
	Price *int32 `db:"price" json:"price"`
	// メモ（最大500文字）
	Memo *string `db:"memo" json:"memo"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	// 更新日時
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// お酒画像
type SakeImage struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// 画像オブジェクトキー
	ImageKey string `db:"image_key" json:"image_key"`
	// 表示順（0始まり）
	SortOrder int32 `db:"sort_order" json:"sort_order"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// お酒タグマスタ
type SakeTag struct {
	// タグID
	ID pgtype.UUID `db:"id" json:"id"`
	// タグ文字列（最大50文字, 必須）
	Tag string `db:"tag" json:"tag"`
}

// お酒とタグの関連
type SakeTagLink struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// お酒ID
	SakeID pgtype.UUID `db:"sake_id" json:"sake_id"`
	// タグID
	SakeTagID pgtype.UUID `db:"sake_tag_id" json:"sake_tag_id"`
}

// ユーザー
type User struct {
	// 一意識別子
	ID pgtype.UUID `db:"id" json:"id"`
	// メールアドレス（必須, 一意）
	Email string `db:"email" json:"email"`
	// パスワードハッシュ（必須）
	PasswordHash string `db:"password_hash" json:"password_hash"`
	// 表示名（任意）
	DisplayName *string `db:"display_name" json:"display_name"`
	// ロール（SHOP/USER）
	Role RoleType `db:"role" json:"role"`
	// 作成日時
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
