// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountSakes(ctx context.Context, category NullSakeCategory) (int64, error)
	CreateSake(ctx context.Context, arg CreateSakeParams) (CreateSakeRow, error)
	DeleteSake(ctx context.Context, id pgtype.UUID) (int64, error)
	GetSakeDetailByID(ctx context.Context, id pgtype.UUID) (GetSakeDetailByIDRow, error)
	ListSakes(ctx context.Context, arg ListSakesParams) ([]ListSakesRow, error)
	UpdateSake(ctx context.Context, arg UpdateSakeParams) (UpdateSakeRow, error)
}

var _ Querier = (*Queries)(nil)
