// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountSakes(ctx context.Context, arg CountSakesParams) (int64, error)
	CreateLike(ctx context.Context, arg CreateLikeParams) error
	CreateSake(ctx context.Context, arg CreateSakeParams) (CreateSakeRow, error)
	DeleteLike(ctx context.Context, arg DeleteLikeParams) (int64, error)
	DeleteSake(ctx context.Context, id int32) (int64, error)
	DeleteSakeDrinkStyles(ctx context.Context, sakeID int32) error
	ExistsLike(ctx context.Context, arg ExistsLikeParams) (bool, error)
	GetDrinkStylesBySakeID(ctx context.Context, sakeID int32) ([]GetDrinkStylesBySakeIDRow, error)
	GetLikeCount(ctx context.Context, sakeID int32) (int64, error)
	GetSakeDetailByID(ctx context.Context, arg GetSakeDetailByIDParams) (GetSakeDetailByIDRow, error)
	GetSakeKindByName(ctx context.Context, name string) (GetSakeKindByNameRow, error)
	GetSakeObjectKey(ctx context.Context, id int32) (*string, error)
	InsertSakeDrinkStyle(ctx context.Context, arg InsertSakeDrinkStyleParams) error
	ListBreweries(ctx context.Context, arg ListBreweriesParams) ([]ListBreweriesRow, error)
	ListDrinkStyles(ctx context.Context) ([]ListDrinkStylesRow, error)
	ListKinds(ctx context.Context) ([]ListKindsRow, error)
	ListSakes(ctx context.Context, arg ListSakesParams) ([]ListSakesRow, error)
	UpdateSake(ctx context.Context, arg UpdateSakeParams) (UpdateSakeRow, error)
	UpdateSakeObjectKey(ctx context.Context, arg UpdateSakeObjectKeyParams) (int64, error)
	UpsertBrewery(ctx context.Context, arg UpsertBreweryParams) (int32, error)
	UpsertDrinkStyle(ctx context.Context, arg UpsertDrinkStyleParams) (int32, error)
	UpsertSakeKind(ctx context.Context, name string) (int32, error)
}

var _ Querier = (*Queries)(nil)
