// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sakes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSakes = `-- name: CountSakes :one
SELECT COUNT(*) AS total
FROM sakes s
WHERE
    ($1::sake_category IS NULL OR s.category = $1)
`

func (q *Queries) CountSakes(ctx context.Context, category NullSakeCategory) (int64, error) {
	row := q.db.QueryRow(ctx, countSakes, category)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSake = `-- name: CreateSake :one
INSERT INTO sakes (category, name, phonetic, alcohol_percentage, volume_max, volume_remain, region, price, memo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, category, name, created_at, updated_at
`

type CreateSakeParams struct {
	Category          SakeCategory   `db:"category" json:"category"`
	Name              string         `db:"name" json:"name"`
	Phonetic          *string        `db:"phonetic" json:"phonetic"`
	AlcoholPercentage pgtype.Numeric `db:"alcohol_percentage" json:"alcohol_percentage"`
	VolumeMax         *int32         `db:"volume_max" json:"volume_max"`
	VolumeRemain      *int32         `db:"volume_remain" json:"volume_remain"`
	Region            *string        `db:"region" json:"region"`
	Price             *int32         `db:"price" json:"price"`
	Memo              *string        `db:"memo" json:"memo"`
}

type CreateSakeRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Category  SakeCategory       `db:"category" json:"category"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSake(ctx context.Context, arg CreateSakeParams) (CreateSakeRow, error) {
	row := q.db.QueryRow(ctx, createSake,
		arg.Category,
		arg.Name,
		arg.Phonetic,
		arg.AlcoholPercentage,
		arg.VolumeMax,
		arg.VolumeRemain,
		arg.Region,
		arg.Price,
		arg.Memo,
	)
	var i CreateSakeRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSake = `-- name: DeleteSake :execrows
DELETE FROM sakes WHERE id = $1
`

func (q *Queries) DeleteSake(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSake, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSakeDetailByID = `-- name: GetSakeDetailByID :one
SELECT
    s.id,
    s.category,
    s.name,
    s.phonetic,
    s.alcohol_percentage,
    s.volume_max,
    s.volume_remain,
    s.region,
    s.memo,
    s.price,
    s.created_at,
    s.updated_at
FROM sakes s
WHERE s.id = $1
`

type GetSakeDetailByIDRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Category          SakeCategory       `db:"category" json:"category"`
	Name              string             `db:"name" json:"name"`
	Phonetic          *string            `db:"phonetic" json:"phonetic"`
	AlcoholPercentage pgtype.Numeric     `db:"alcohol_percentage" json:"alcohol_percentage"`
	VolumeMax         *int32             `db:"volume_max" json:"volume_max"`
	VolumeRemain      *int32             `db:"volume_remain" json:"volume_remain"`
	Region            *string            `db:"region" json:"region"`
	Memo              *string            `db:"memo" json:"memo"`
	Price             *int32             `db:"price" json:"price"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetSakeDetailByID(ctx context.Context, id pgtype.UUID) (GetSakeDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getSakeDetailByID, id)
	var i GetSakeDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Name,
		&i.Phonetic,
		&i.AlcoholPercentage,
		&i.VolumeMax,
		&i.VolumeRemain,
		&i.Region,
		&i.Memo,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSakes = `-- name: ListSakes :many
SELECT
    s.id,
    s.category,
    s.name,
    si.image_key
FROM sakes s
LEFT JOIN sake_images si ON si.sake_id = s.id AND si.sort_order = 0
WHERE
    ($3::sake_category IS NULL OR s.category = $3)
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSakesParams struct {
	Limit    int32            `db:"limit" json:"limit"`
	Offset   int32            `db:"offset" json:"offset"`
	Category NullSakeCategory `db:"category" json:"category"`
}

type ListSakesRow struct {
	ID       pgtype.UUID  `db:"id" json:"id"`
	Category SakeCategory `db:"category" json:"category"`
	Name     string       `db:"name" json:"name"`
	ImageKey *string      `db:"image_key" json:"image_key"`
}

func (q *Queries) ListSakes(ctx context.Context, arg ListSakesParams) ([]ListSakesRow, error) {
	rows, err := q.db.Query(ctx, listSakes, arg.Limit, arg.Offset, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSakesRow
	for rows.Next() {
		var i ListSakesRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.ImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSake = `-- name: UpdateSake :one
UPDATE sakes
SET category = $2,
    name = $3,
    phonetic = $4,
    alcohol_percentage = $5,
    volume_max = $6,
    volume_remain = $7,
    region = $8,
    price = $9,
    memo = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, category, name, created_at, updated_at
`

type UpdateSakeParams struct {
	ID                pgtype.UUID    `db:"id" json:"id"`
	Category          SakeCategory   `db:"category" json:"category"`
	Name              string         `db:"name" json:"name"`
	Phonetic          *string        `db:"phonetic" json:"phonetic"`
	AlcoholPercentage pgtype.Numeric `db:"alcohol_percentage" json:"alcohol_percentage"`
	VolumeMax         *int32         `db:"volume_max" json:"volume_max"`
	VolumeRemain      *int32         `db:"volume_remain" json:"volume_remain"`
	Region            *string        `db:"region" json:"region"`
	Price             *int32         `db:"price" json:"price"`
	Memo              *string        `db:"memo" json:"memo"`
}

type UpdateSakeRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Category  SakeCategory       `db:"category" json:"category"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateSake(ctx context.Context, arg UpdateSakeParams) (UpdateSakeRow, error) {
	row := q.db.QueryRow(ctx, updateSake,
		arg.ID,
		arg.Category,
		arg.Name,
		arg.Phonetic,
		arg.AlcoholPercentage,
		arg.VolumeMax,
		arg.VolumeRemain,
		arg.Region,
		arg.Price,
		arg.Memo,
	)
	var i UpdateSakeRow
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
