// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sakes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSakes = `-- name: CountSakes :one
SELECT COUNT(*) AS total
FROM sakes
WHERE
    ($1::sake_category IS NULL OR category = $1)
`

func (q *Queries) CountSakes(ctx context.Context, category NullSakeCategory) (int64, error) {
	row := q.db.QueryRow(ctx, countSakes, category)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createSake = `-- name: CreateSake :one
INSERT INTO sakes (name, phonetic, image_id, category, description, alcohol_percentage, volume_max, volume_remain, region, price, memo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at, updated_at
`

type CreateSakeParams struct {
	Name              string         `db:"name" json:"name"`
	Phonetic          *string        `db:"phonetic" json:"phonetic"`
	ImageID           pgtype.UUID    `db:"image_id" json:"image_id"`
	Category          SakeCategory   `db:"category" json:"category"`
	Description       *string        `db:"description" json:"description"`
	AlcoholPercentage pgtype.Numeric `db:"alcohol_percentage" json:"alcohol_percentage"`
	VolumeMax         *int32         `db:"volume_max" json:"volume_max"`
	VolumeRemain      *int32         `db:"volume_remain" json:"volume_remain"`
	Region            *string        `db:"region" json:"region"`
	Price             *int32         `db:"price" json:"price"`
	Memo              *string        `db:"memo" json:"memo"`
}

type CreateSakeRow struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt time.Time   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSake(ctx context.Context, arg CreateSakeParams) (CreateSakeRow, error) {
	row := q.db.QueryRow(ctx, createSake,
		arg.Name,
		arg.Phonetic,
		arg.ImageID,
		arg.Category,
		arg.Description,
		arg.AlcoholPercentage,
		arg.VolumeMax,
		arg.VolumeRemain,
		arg.Region,
		arg.Price,
		arg.Memo,
	)
	var i CreateSakeRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const deleteSake = `-- name: DeleteSake :exec
DELETE FROM sakes WHERE id = $1
`

func (q *Queries) DeleteSake(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSake, id)
	return err
}

const getSakeByID = `-- name: GetSakeByID :one
SELECT id, name, phonetic, image_id, category, description, alcohol_percentage, volume_max, volume_remain, region, price, memo, created_at, updated_at
FROM sakes
WHERE id = $1
`

func (q *Queries) GetSakeByID(ctx context.Context, id pgtype.UUID) (Sake, error) {
	row := q.db.QueryRow(ctx, getSakeByID, id)
	var i Sake
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phonetic,
		&i.ImageID,
		&i.Category,
		&i.Description,
		&i.AlcoholPercentage,
		&i.VolumeMax,
		&i.VolumeRemain,
		&i.Region,
		&i.Price,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSakes = `-- name: ListSakes :many
SELECT id, name, phonetic, image_id, category, description, alcohol_percentage, volume_max, volume_remain, region, price, memo, created_at, updated_at
FROM sakes
WHERE
    ($3::sake_category IS NULL OR category = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSakesParams struct {
	Limit    int32            `db:"limit" json:"limit"`
	Offset   int32            `db:"offset" json:"offset"`
	Category NullSakeCategory `db:"category" json:"category"`
}

func (q *Queries) ListSakes(ctx context.Context, arg ListSakesParams) ([]Sake, error) {
	rows, err := q.db.Query(ctx, listSakes, arg.Limit, arg.Offset, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sake
	for rows.Next() {
		var i Sake
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phonetic,
			&i.ImageID,
			&i.Category,
			&i.Description,
			&i.AlcoholPercentage,
			&i.VolumeMax,
			&i.VolumeRemain,
			&i.Region,
			&i.Price,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSake = `-- name: UpdateSake :exec
UPDATE sakes
SET name = $2, phonetic = $3, image_id = $4, category = $5, description = $6, alcohol_percentage = $7, volume_max = $8, volume_remain = $9, region = $10, price = $11, memo = $12, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateSakeParams struct {
	ID                pgtype.UUID    `db:"id" json:"id"`
	Name              string         `db:"name" json:"name"`
	Phonetic          *string        `db:"phonetic" json:"phonetic"`
	ImageID           pgtype.UUID    `db:"image_id" json:"image_id"`
	Category          SakeCategory   `db:"category" json:"category"`
	Description       *string        `db:"description" json:"description"`
	AlcoholPercentage pgtype.Numeric `db:"alcohol_percentage" json:"alcohol_percentage"`
	VolumeMax         *int32         `db:"volume_max" json:"volume_max"`
	VolumeRemain      *int32         `db:"volume_remain" json:"volume_remain"`
	Region            *string        `db:"region" json:"region"`
	Price             *int32         `db:"price" json:"price"`
	Memo              *string        `db:"memo" json:"memo"`
}

func (q *Queries) UpdateSake(ctx context.Context, arg UpdateSakeParams) error {
	_, err := q.db.Exec(ctx, updateSake,
		arg.ID,
		arg.Name,
		arg.Phonetic,
		arg.ImageID,
		arg.Category,
		arg.Description,
		arg.AlcoholPercentage,
		arg.VolumeMax,
		arg.VolumeRemain,
		arg.Region,
		arg.Price,
		arg.Memo,
	)
	return err
}
