openapi: 3.0.3
info:
  title: Sake Hack Backend API
  version: 1.0.0
  description: |
    Sake Hack Backend API
  contact:
    name: Sake Hack Team
servers:
  - url: http://localhost:8080/api
    description: Local development server

paths:
  /kinds:
    $ref: "./paths/kinds.yaml"
  /breweries:
    $ref: "./paths/breweries.yaml"
  /drink-styles:
    $ref: "./paths/drinkStyles.yaml"
  /sakes:
    $ref: "./paths/sakes.yaml"
  /sakes/{id}:
    $ref: "./paths/sakeDetail.yaml"
  /sakes/{id}/likes:
    $ref: "./paths/sakeLikes.yaml"
  /stocks:
    $ref: "./paths/stocks.yaml"
  /stocks/{id}:
    $ref: "./paths/stockDetail.yaml"
  /stocks/{id}/upload-url:
    $ref: "./paths/stockUploadUrl.yaml"

components:
  securitySchemes:
    BearerAuth:
      $ref: "./components/securitySchemes/auth.yaml#/BearerAuth"

tags:
  - name: Master
    description: マスタデータ関連
  - name: Sakes
    description: 酒関連
  - name: Likes
    description: いいね関連
  - name: Stocks
    description: 在庫関連
