openapi: 3.0.3
info:
  title: Sake Hack Backend API
  version: 1.0.0
  description: |
    Sake Hack Backend API
  contact:
    name: Sake Hack Team
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /sakes:
    $ref: "./paths/sakes.yaml"
  /sakes/{id}:
    $ref: "./paths/sakeDetail.yaml"

tags:
  - name: Sake
    description: 酒関連API
