openapi: 3.0.3
info:
  title: Sake Hack Backend API
  version: 1.0.0
  description: |
    Sake Hack Backend API
  contact:
    name: Sake Hack Team
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /sakes:
    $ref: "./paths/sakes.yaml"
  /sakes/{id}:
    $ref: "./paths/sakeDetail.yaml"
  /stocks:
    $ref: "./paths/stocks.yaml"
  /stocks/{id}:
    $ref: "./paths/stockDetail.yaml"

tags:
  - name: Sakes
    description: 酒関連API（公開閲覧用）
  - name: Stocks
    description: 在庫管理API（店舗用）
